### ISSUE TITLE
Generate EEPROM map for MakerBot Desktop?

### ISSUE THREAD

**Issue by rpavlik** [jetty840/Sailfish-MightyBoardFirmware#191]
The files at the ReplicatorG-Sailfish "thing" are fairly old, and so I'm not confident that they match the current "tip-of-tree" firmware I've built and installed. And, despite the README there saying it's integrated, MakerBot Desktop 3.10.0.1364 complains it doesn't have EEPROM maps for my device (a Replicator 2X, with upgraded sailfish firmware) if I try to edit parameters. (It also doesn't let me unload filament from the app? Not sure if that's related - I couldn't get makerbot desktop to connect with the original MBI firmware so 🤷‍♂️ )

It looks like there is markup to automatically generate the files required, however, the only script I see in this repo takes in a CSV file, not a header file.

Any advice on how I can do this? (Or, alternately: it doesn't look like the eeprommaps file has changed much, perhaps I can just minimally modify the 7.7 file to identify itself as 7.8?)

EDIT: Here's the log from the "background service" - I know this isn't MBI support, but it might be useful in some way perhaps...

```
2017-12-28 12:10:33,316 | INFO | MainThread:18316 | main.py:227 | conveyor.server.__main__.ServerMain:_log_startup | conveyord 3.8.4 started
2017-12-28 12:10:33,316 | INFO | MainThread:18316 | main.py:228 | conveyor.server.__main__.ServerMain:_log_startup | git hash: 945ad3e8970c81a794328e470bd8a389bb5a21b9
2017-12-28 12:10:33,316 | INFO | MainThread:18316 | main.py:229 | conveyor.server.__main__.ServerMain:_log_startup | process id: 28304
2017-12-28 12:10:33,316 | INFO | MainThread:18316 | main.py:230 | conveyor.server.__main__.ServerMain:_log_startup | python version: '2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]'
2017-12-28 12:10:33,322 | INFO | MainThread:18316 | main.py:231 | conveyor.server.__main__.ServerMain:_log_startup | python platform: 'Windows-8-6.2.9200'
2017-12-28 12:10:33,322 | INFO | MainThread:18316 | main.py:232 | conveyor.server.__main__.ServerMain:_log_startup | python pointer size: 64
2017-12-28 12:10:33,673 | INFO | MainThread:18316 | __main__.py:57 | conveyor.server.__main__.ServerMain:_run | Listening for client connections
2017-12-28 12:10:33,953 | INFO | MainThread:18316 | __init__.py:1536 | conveyor.server.Server:usb_device_inserted | Device {u'iserial': 'XXXXXXXXXXXX', u'pid': 45079, u'port_type': 'UsbPort', u'vid': 9153} inserted
2017-12-28 12:10:34,364 | ERROR | MainThread:18316 | EepromReader.py:47 | EepromReader:__init__ | Could not find C:\Program Files\MakerBot\MakerWare\python\makerbot_driver-0.1.1-py2.7.egg\makerbot_driver\EEPROM\eeprom_map_708_0x00.json
2017-12-28 12:10:34,446 | INFO | MainThread:18316 | s3g.py:360 | conveyor.machine.s3g._S3gMachine:connect | Connecting {u'can_print': True, u'number_of_toolheads': 2, u'display_name': 'Replicator 2X', u'name': {u'iserial': 'XXXXXXXXXXXX', u'pid': 45079, u'port_type': 'UsbPort', u'vid': 9153}, u'platform_temperature': 15, u'has_heated_platform': True, u'profile_name': u'Replicator2X', u'toolhead_target_temperature': [0, 0], u'build_volume': [246, 152, 155], u'state': u'IDLE', u'driver_name': u's3g', u'printer_type': u'The Replicator 2X', u'firmware_version': [7, 8], u'toolhead_temperature': [22, 22]}
2017-12-28 12:10:34,447 | INFO | MainThread:18316 | listener.py:105 | conveyor.listener.TcpListener:_log_connection | Accepted ('127.0.0.1', 49067) listener
2017-12-28 12:10:34,976 | WARNING | event_thread-3:19500 | jsonrpc.py:399 | conveyor.jsonrpc.JsonRpc:_invokemethod | uncaught exception
Traceback (most recent call last):
  File "python\conveyor-3.8.4-py2.7.egg\conveyor\jsonrpc.py", line 389, in _invokemethod
    result = func(*args, **kwargs)
  File "python\conveyor-3.8.4-py2.7.egg\conveyor\server\__init__.py", line 2463, in first_contact
    return self._server.first_contact(machine_name)
  File "python\conveyor-3.8.4-py2.7.egg\conveyor\server\__init__.py", line 628, in first_contact
    return machine.first_contact()
AttributeError: '_S3gMachine' object has no attribute 'first_contact'
2017-12-28 12:10:52,592 | ERROR | work-thread-23C1:B017:64936333137351E0B160:1056 | EepromReader.py:47 | EepromReader:__init__ | Could not find s3g/EEPROM/eeprom_map_7.8_0x80.json
2017-12-28 12:10:52,592 | WARNING | work-thread-23C1:B017:64936333137351E0B160:1056 | s3g.py:1462 | conveyor.machine.s3g._ReadEepromOperation:_run_without_polling | handled exception
Traceback (most recent call last):
  File "python\conveyor-3.8.4-py2.7.egg\conveyor\machine\s3g.py", line 1459, in _run_without_polling
    self.machine._s3g, version, software_variant, working_directory)
  File "python\makerbot_driver-0.1.1-py2.7.egg\makerbot_driver\EEPROM\EepromReader.py", line 26, in factory
    eeprom_reader = makerbot_driver.EEPROM.EepromReader(map_name, working_directory)
  File "python\makerbot_driver-0.1.1-py2.7.egg\makerbot_driver\EEPROM\EepromReader.py", line 48, in __init__
    raise makerbot_driver.EEPROM.MissingEepromMapError(path)
MissingEepromMapError
`

**Comment by rpavlik** [comment]
Ahh, it appears related to the EepromAnalyzer.py tool included in the makerbot software. I'll still accept hints, but I'll also accept if you want to close this as not-a-bug (though documentation would be handy)

**Comment by dcnewman** [comment]
That EepromAnalyzer.py was some half-finished stuff MakerBot wrote back in the MakerWare days.  It never worked well.  I'd fire it up, get it to run, get a map, clean it up, and send it to MakerBot.  I stopped doing that when they renamed MakerWare to Desktop and made it clear that they no longer wanted to support anything other than their 5th Gen printers.  (Since they still were selling the Rep2X they reluctantly had some support for it in Desktop.)

FWIW, here's a URL for a copy of [`makerbot_driver/EEPROM/EepromAnalyzer.py`](https://www.dropbox.com/s/joofudedky6h63e/EepromAnalyzer.py?dl=0) I have from the s3g-surprise repo.

But no real hints.  MakerBot seemed content with the tool in a so-so state.  And I didn't want to expend any of my time cleaning it up given that they might completely change their map files without notice.
